### ISSUE TITLE
Enhancement - add Close Wall Gaps button

### ISSUE THREAD

**Issue by itamarcu** [flamewave000/dragonflagon-arch#115]
I made a macro for myself but it would probably fit better as part of a module, and this is the module that seemed most fitting for it.

**Close Wall Gaps**
A button in the Walls controls allows you to automatically find and fix all "wall gaps" - places where two walls have their endpoints almost at the same place, off by a small number of pixels. This will show you a preview and a count of how many gaps are about to be closed.

Could also be implemented as an automatic step when editing the scene in some way.

![](https://camo.githubusercontent.com/acd6a63b10ece8fa6e976ebacd9bd0550d6e2b945211e9dfe0d2a5d0fab3ee33/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3639393735303135303637343937323734332f3838383534393730343430333636343930362f756e6b6e6f776e2e706e67)

Demo - https://cdn.discordapp.com/attachments/734095524822777976/888558689873719306/CloseWallGaps3.webp

Source code - https://github.com/itamarcu/shemetz-macros/blob/master/scripts/walls/close-wall-gaps.js

**Comment by Shuggaloaf** [comment]
This is great @itamarcu! 

Just to add my 2 cents, I'd love to see this is the module FW.

**Comment by flamewave000** [comment]
@itamarcu I've gone ahead and added this feature in. I used a fairly different approach to the wall gap detection that I hope is maybe a little easier to read and follow. I also added a small improvement that should reduce the detection time by almost half by reducing the list size by 1 on every comparison. Please feel free to check out the commit and let me know if you see anything worth improving :+1:

Also, since I used your macro as a reference, I've included you in the contributor list.
