### ISSUE TITLE
flattening tiles: background color instead of transparent

### ISSUE THREAD

**Issue by chrisjbrown** [flamewave000/dragonflagon-arch#131]
**Describe the issue**
flattening two tiles together leaves a large grey border around the tiles

**To Reproduce**
1. flatten tiles with two tiles
2. see grey broder around tiles

**Expected behavior**
area around tiles is transparent

**Screenshots (Optional)**
![two-tiles](https://user-images.githubusercontent.com/1250638/174426331-fac45e76-bebd-40fc-b63f-773caae963d8.PNG)

**Comment by flamewave000** [comment]
This would be due to either settings, or another module is preventing me from making the canvas transparent when rendering. Please retry this with all other modules disabled, and if it works, then you can use Find the Culprit to figure out which module is causing the issue. It is most likely a module that modify vision or lighting.

**Comment by chrisjbrown** [comment]
Thanks! yep I use the perfect vision module. turning that off and flattening worked as expected
