### ISSUE TITLE
[PF2E] Canvas does not render with Architect enabled

### ISSUE THREAD

**Issue by grankless** [flamewave000/dragonflagon-arch#29]
`fix.js:36 Uncaught (in promise) TypeError: _sources.set is not a function
    at LightingLayer.<anonymous> (fix.js:36)
    at LightingLayer.wrapper (patch.js:38)
    at O.call_wrapper (wrapper.js:421)
    at LightingLayer.🎁@handler0(LightingLayer.prototype.refresh) (wrapper.js:133)
    at Canvas.initializeSources (foundry.js:10298)
    at Canvas._initialize (foundry.js:10270)
    at Canvas.draw (foundry.js:10199)
    at async Scene.view (foundry.js:34080)`

This is the error I get in console. A scene will load, but I am not able to see the map, tokens, or any drawings. This is on Forge.

**Comment by flamewave000** [comment]
This appears to be a conflict caused by another module and not an issue with DF Architect and PF2e. Could you use the "Find the Culprit" module to find which one is causing the issues?

When Find the Culprit prompts you with "Choose modules to keep active", make sure Architect and its 2 dependency are selected:
- DF Architect
- Library: DF Hotkeys
- libWrapper

**Comment by grankless** [comment]
The culprit turned out to be.... Perfect Vision! Womp womp womp.

**Comment by franckflo** [comment]
I get the same issue without using Forge. I however do use Perfect Vision as well.

**Comment by krysztalzg** [comment]
Can confirm clash with Perfect Vision module

**Comment by flamewave000** [comment]
Yeah, Perfect Vision does some very heavy handed patching of the Foundry core and is already known to conflict. There's a conflict reported for it here: #31
