### ISSUE TITLE
Capture Canvas PPI hardcoded to 96?

### ISSUE THREAD

**Issue by ggagnon76** [flamewave000/dragonflagon-arch#51]
I was using your DF Architect module to assemble a scene from tile pieces, then capturing the canvas to produce an image file I then intended to use as a background.

Everything I was doing was set to 100ppi.  When I captured the canvas using your module and opened it into a photo editor, the resulting image was set to 96ppi and there was a blank border around the top and right of the image.

It was a couple extra steps to crop out the image and resize it, not the end of the world.  But it would be super convenient if the resolution (?) matched the resolution set in the Foundry Scene.

It would also be super useful to be able to name the captured image prior to it being saved.

**Comment by flamewave000** [comment]
I'll try to address each part of your post here:

- **PPI:** I'm not sure why the resolution would change. Honestly the PPI is technically an arbitrary number only used by printers and photo editing software. 96 is actually the generic resolution of all computer monitors, so it makes sense that the GPU would use that by default. ([You can find more info on that subject in this discussion](https://stackoverflow.com/questions/27323561/do-pngs-or-jpgs-have-a-dpi-or-is-it-irrelevant-when-building-for-retina))
- **Blank Border:** That is most likely due to the canvas being too large to render into a single image. There are limits to what the GPU can do. If you need to render the whole thing and are seeing those blank spaces, I recommend using the subdivision feature to render it into two halves of the image (or quarters if it is really big). This will avoid the render limit problem. I do have a warning in the dialog about this unavoidable issue when rendering the entire canvas.
- **File Name:** I could provide a textbox in the dialog for defining your own name for the file download, though you can technically change the name when the file begins to download if you change your browser's download settings.

**Comment by ggagnon76** [comment]
The File Name would be a nice to have.  Not critical.

As for the PPI, it's confusing to generate the capture using a 100ppi setting, import the image as a background and then have to go change scene settings to 96ppi for the grids to match.

Blank Border:   It is not an issue of my scene being too big.  I was making scenes that were 400x400 @ 100 ppi and it was still generating that border.  I will try to make a video showing this to attach to this issue.

**Comment by flamewave000** [comment]
**PPI:** Foundry doesn't use an image's PPI for determining the grid size. Grid size is 100 by default for all scenes. I just saved my test game board as PNG and JPEG and the saved images have the grid lines still at exactly 100 pixels. The file's meta-data says 96dpi though, but again that's an arbitrary value that only graphics editing programs and printers use. When a picture is on a monitor, every pixel is a pixel, and the foundry grid aligns to pixels and not to the DPI of the image.
![image](https://user-images.githubusercontent.com/3588046/125644940-8d5edfc3-2d09-4c1c-85d4-d78015432667.png)

**Blank Border:** I've only ever seen this occur on maps that were too large to render. I've tried a 400x400 image without any issue. Does this happen consistently? If so, it might be something odd happening with your GPU. Also make sure you don't have the "Include Padding" option checked, as that will include the padded area around the scene.

**Comment by flamewave000** [comment]
As for the DPI meta data, if this is an annoyance for when you are opening the image in a Graphics Editor, or printing it, I can see if I can maybe modify the image data to set the PPI to what ever the grid size is. There are no configurations for that when I am pulling the image from the GPU, but I could try to modify the raw file data to change it.

**Comment by ggagnon76** [comment]
I will make a video to show you.  I made 6 scenes this way, and it took several tries to sort out the workflow for the first one.  The blank border happened on every attempt.  All the scenes I captured had no padding.  The only reason I realized the saved image has 96ppi is because I had to crop and resize them because of the blank (transparent) border.

**Comment by ggagnon76** [comment]
I am not overly concerned with the DPI meta data.  If I can capture the scene, then assign it as a background and everything just works, I'm happy.

**Comment by ggagnon76** [comment]
Oh, one other bit of info that is probably pertinent:   I was saving as webp.

I did not try with other formats.

**Comment by flamewave000** [comment]
Hmm ok, so WebP is only supported by Chromium, and is a bit experimental. Try with PNG or JPEG to see if they have the same issue. If they do, it's likely something going on with your GPU and I may not be able to do anything for that unfortunately. If it doesn't happen for PNG and JPEG, you'll likely just have to use either of those and convert the image to WebP after or something.

**Comment by ggagnon76** [comment]
https://user-images.githubusercontent.com/77990156/125722024-968da7a6-0de8-407b-979c-9fe95b7d4b0e.mp4

**Comment by ggagnon76** [comment]
![image](https://user-images.githubusercontent.com/77990156/125723559-34dac6a3-ef4b-4706-8ab4-407da5b17259.png)
Tested again, with only these modules.

**Comment by flamewave000** [comment]
Thank you for the video. I'm not sure why this is happening to you. The 585 resolution is definitely very strange. The 96dpi won't be causing any issues since it's arbitrary. But that blank space on the top and right is extremely odd. I'm not sure why this is happening to you. Does this happen for larger images? or just small ones?
Also, do you have hardware acceleration turned on for your browser?

**Comment by ggagnon76** [comment]
Well, some progress:

This map is 4500 x 3500 pixels:

![image](https://user-images.githubusercontent.com/77990156/125875643-b61b4649-5d74-4099-ac4e-bfad71e37b84.png)

In Microsoft Edge (chromium), the map has the blank border (screenshot above).  Hardware acceleration is turned on.

In Chrome, the map doesn't have a blank border.  Hardware acceleration is turned on.

**Comment by flamewave000** [comment]
Interesting, so I haven't used Edge  since I switched to Brave, but I tried it and it doesn't seem to give me that issue either. Maybe there is something wonky going on with your version of Edge then. To explain how the image size is done, I have to resize the HTML Canvas element to the exact pixel size I want to save, and then I request the rendered image from the GPU (via the PIXI library that Foundry uses). My best guess is that for some reason Edge is oversizing the canvas element and not respecting the dimensions I'm setting.

If Brave, Firefox, or Chrome work for you, could you use one of them as an alternative? Edge may just be having a temporary issue that'll maybe get updated in the future.

**Comment by ggagnon76** [comment]
This is not a feature that I use often, so even if I had to crop and resave, it wouldn't be a show stopper.  But knowing it works properly in Chrome is an option to save time.  I only just switched to Edge because supposedly it's less of a resource hog.

I reported this issue so you can be aware this happens.  Feel free to close this issue if you can't pursue it further.

**Comment by flamewave000** [comment]
Sounds good 👍🏽 Yeah I'll close the ticket as I have #52 to track your other suggestion for the file name.
