### ISSUE TITLE
Short summary of the issue...

### ISSUE THREAD

**Issue by Nargath** [flamewave000/dragonflagon-arch#58]
Foundry: 0.8.9
DF Architect: 2.1.2

**Describe the issue**
Lighting functionalities no longer work on some of my 0.8.9 worlds.

This includes the ability to set darkness inside a light's settings, the ability to save it as a template and to re-use that template by CTRL-Clicking on the light layer.
Even the ability to see the light origin when moving a light.

However none of the other functions, including walls and the items in compendiums, are affected.

I moved my server host, and took a backup of all my data from one server, and copied it to the new server.
The only difference between the two, was that the first server was 0.8.8 Foundry, and the newer one was 0.8.9.
One campaign, where the light settings were working prior to relocation, was created under 0.8.8, and then was migrated to 0.8.9 once I re-opened it under the new server.
However on another campaign world, that ALSO was converted the same way as above, and its DF Architect lighting functions work properly.

I have used Find The Culprit with DF Architect and its dependacies kept on, and even with all other modules off, the lighting functions are not available.

The other thing that I only see on the broken world, is the below error in the console.
It does not appear on 0.8.9 worlds that have their lighting functions working.

Could there be an issue with the conversion process that's either broke or didn't run properly on the world that doesn't have the functionality working?

**Screenshots (Optional)**
![Screenshot 2021-09-23 013833](https://user-images.githubusercontent.com/5538979/134375583-a8c5ad75-d523-4a65-940c-9783484a765b.png)

![Screenshot 2021-09-23 013842](https://user-images.githubusercontent.com/5538979/134375602-dc894409-84ca-45ac-a2c0-3ed2a056063e.png)

**Comment by flamewave000** [comment]
Unfortunately I'm not sure what to tell you for this. I don't do any data migration because the light templates are just plain JavaScript Macros that I detect and provide specialized UI for. The error you see also surprises me as that is the section that patches the Mouse Interaction Manager for doing the Ctrl Invert feature. Those "callbacks" should exist as they are generated when Foundry first loads.

The symptoms of not being able to see the UI and some of the features not functioning is indicative of a crash in the script. Could you scroll up to the top of the Dev Console and see if there are any other errors there? You should see an ASCii graphic that says ARCHITECT when the module first begins to load.

**Comment by Nargath** [comment]
There are other errors, but related to about time failing to load a calendar, and Rounded Distance for Measured Templates. And they occur well after DF Architect loads.
I can definitely see your ASCII art load in early on in the console log.

**Comment by flamewave000** [comment]
Could you retry this? I've put some safeties around my features that should allow one feature to fail without affecting the others. I'm still not sure why you are getting this issue as I can't reproduce it on my side.
