### ISSUE TITLE
Tile Flattener - Image not capturing full scene canvas

### ISSUE THREAD

**Issue by Keatnisher** [flamewave000/dragonflagon-arch#80]
**Describe the issue**
Tile flattener cuts out the edges of the scene for full canvas. At 2000x2000 scene, flattener only renders 1701x1701. at 4000x3000, only 3240x2430 is rendered. Scene padding has no impact that I have observed. The top and right of the scene is cut off, left and bottom is retained.

Brave | 1.30.89 Chromium: 94.0.4606.81 (Official Build) (64-bit)

**To Reproduce**
Flatten Tiles - Regardless of file format, quality of file, browser (tested between Brave and Chrome), or save location (save on computer and all save on server options)

Image is rendered and savable.

![input](https://user-images.githubusercontent.com/26535174/138004124-6a65bbcf-7a83-49e2-af1c-6a769abcce96.png)

**Expected behavior**
Full scene image rendered.

**Screenshots (Optional)**
Possibly-related error in console:

![Screenshot from 2021-10-19 19-50-39](https://user-images.githubusercontent.com/26535174/138005718-bfdf82b8-4cbf-409b-998f-124e8adecbc0.png)

P.S. thanks for the last fix! I'm able to save images now, but.. not completely haha

**Comment by flamewave000** [comment]
Well, I'm a little bit confused as to why your LightingLayer is missing. What System are you using? The LightingLayer is the layer used for all Lights.

**Comment by flamewave000** [comment]
So it looks like pf2e does in fact destroy the entire Foundry LightingLayer, then they monkey patch their own custom LightingLayerPF2e into the canvas. This is where all of the issues are arising. This is a very bizarre and surprising thing for them to be doing. It means having to put System Specific code into my otherwise completely System-Agnostic module which does not make me happy at all.

I know I'm venting a little, but this is pretty ridiculous that the system devs would do something so terribly breaking to FoundryVTT.
